/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "uart.h"
#include "led.h"
#include "delay.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	initUsart2();
	initLeds();
	setLeds(0b1111);
	setLeds(0b0110);
	// Clear terminal screen and move cursor to top-left
	printf("\033[2J\033[H");
	printf("Hello World\r\n");
	uint8_t press_count = 0;
	for(int i = 0;; i++) {
		delay_ms(500);
		setLeds(1U << (i % 4));
	}
    /* Loop forever */
	for(;;) {


		press_count++;

		// '\r' returns cursor to start of line (no newline)
		printf("\rButton press count: %u", press_count);

	}

}
